-- Douglas Daniel Aguilar Cuque
-- 201503935
-- Demostrar que las tablas estan vacias 

SELECT * FROM DOCTOR;
SELECT * FROM PACIENTE;
SELECT * FROM FARMACIA;
SELECT * FROM LABORATORIO;
SELECT * FROM MEDICINA;
SELECT * FROM LISTA_PRECIOS;
SELECT * FROM PRESCRIPCION;
QUIT;