

DROP TABLE DOCTOR CASCADE CONSTRAINTS;

DROP TABLE FARMACIA CASCADE CONSTRAINTS;

DROP TABLE LABORATORIO CASCADE CONSTRAINTS;

DROP TABLE LISTA_PRECIOS CASCADE CONSTRAINTS;

DROP TABLE MEDICINA CASCADE CONSTRAINTS;

DROP TABLE PACIENTE CASCADE CONSTRAINTS;

DROP TABLE PRESCRIPCION CASCADE CONSTRAINTS;

SELECT * FROM doctor;
SELECT * FROM paciente;
SELECT * FROM FARMACIA;
SELECT * FROM LABORATORIO;
SELECT * FROM MEDICINA;
SELECT * FROM LISTA_PRECIOS;
SELECT * FROM PRESCRIPCION;
