-- Douglas Daniel Aguilar Cuque
-- 201503935
-- Demostrar que las tablas estan vacias 

SELECT COUNT(*) AS INICIO_DE_DOCTORES FROM DOCTOR;
SELECT COUNT(*) AS INICIO_DE_PACIENTES FROM PACIENTE;
SELECT COUNT(*) AS INICIO_DE_FARMACIAS FROM FARMACIA;
SELECT COUNT(*) AS INICIO_DE_LABORATORIOS FROM LABORATORIO;
SELECT COUNT(*) AS INICIO_DE_MEDICINAS FROM MEDICINA;
SELECT COUNT(*) AS INICIO_DE_LISTAS FROM LISTA_PRECIOS;
SELECT COUNT(*) AS INICIO_DE_PRESCRIPCIONES FROM PRESCRIPCION;
QUIT;